### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by staccDOTsol**
:)))

slerf is satoshi; slerf is jeebus

### CODE REVIEW

**Comment by havan** [comment]
:)) Oh man, I had to use ChatGPT to decrypt what you've wrote. 🤣 

Can we update your thoughts so non-native speakers also understand? :) Also, we need to put those into the timeline to the correct place. I can do those if it's ok with you.

Here's the part from GPT:

## Reflections from Stacc

In a world that thrives on notoriety, there's talk comparing you to legends and figures of monumental change—being called the Satoshi of our times, likened to a modern-day savior. It's both awe-inspiring and overwhelming to witness your journey unfold, filled with its share of folly and wisdom.

Your missteps, while they may seem monumental, have a curious way of making the rest of us feel less alone in our own errors. It's as though your actions have a redemptive quality, elevating you to a status beyond mere mortals, akin to a comedic yet revered figure who's stumbled upon wisdom through chaos.

The tale of Slorg, who metaphorically fell on a sword amidst the turmoil, adds another layer to this saga. The confusion, amplified by media misinterpretations, paints a picture of an unfolding drama that's as absurd as it is captivating.

The term "slerfing it" has become our inside joke, a nod to the unique blend of brilliance and blunder that's come to define this narrative. It's a reminder that even when things seem their worst, there's a communal understanding, a shared laughter at the folly, and a recognition of the humanity in error.

The critiques of a reporter's misunderstanding only underscore the larger movement you've sparked—a testament to turning mishaps into milestones. Despite the weight of these events on your shoulders, your journey symbolizes a collective absolution from our shared misjudgments and follies.

In essence, your path, marked by its highs and lows, becomes a beacon for all of us navigating the tumultuous seas of life. Through the laughter, the mistakes, and the unexpected moments of clarity, we find a sense of camaraderie and hope. In the grand tapestry of life, your story is a vivid thread, weaving together the absurd with the profound, reminding us that redemption lies not in perfection but in embracing our shared humanity.

**Comment by staccDOTsol** [comment]
It's a conversation I had w Slerf himself in DMs on Mar 22

**Comment by staccDOTsol** [comment]
I would rather not update the original quotes as they're verbatim

**Comment by havan** [comment]
@staccDOTsol thanks a lot for the update. If it possible to mark which lines are yours and which ones are slerf's? That would be awesome.

**Pull request merged**
